# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    # Uncomment and specify other tools if required
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt
